#runtime: php
#env: flexible
runtime: php72

#automatic_scaling:
#  min_num_instances: 2
#  max_num_instances: 5

instance_class: B2

basic_scaling:
  max_instances: 10
  idle_timeout: 10m

runtime_config:
    document_root: public
    enable_stackdriver_integration: true

handlers:
- url: /.*
  script: public/index.php

- url: /css
  static_dir: public/css

- url: /img
  static_dir: public/img

- url: /js
  static_dir: public/js

beta_settings:
    cloud_sql_instances: "eloquent-optics-206213:us-east1:twicbdd"
