-- MySQL Script generated by MySQL Workbench
-- jeu. 28 avril 2016 16:33:30 CEST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema inv
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Table `activity`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `activity` ;

CREATE TABLE IF NOT EXISTS `activity` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `event` VARCHAR(255) NULL DEFAULT NULL,
  `object_id` INT(11) NULL DEFAULT NULL,
  `object_name` VARCHAR(255) NULL DEFAULT NULL,
  `object_value` INT(11) NOT NULL DEFAULT '1',
  `object_data` TEXT NULL DEFAULT NULL,
  `target_id` INT(11) NULL DEFAULT NULL,
  `target_name` VARCHAR(255) NULL DEFAULT NULL,
  `target_data` TEXT NULL DEFAULT NULL,
  `date` DATETIME NULL DEFAULT NULL,
  `user_id` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `country`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `country` ;

CREATE TABLE IF NOT EXISTS `country` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `iso2` CHAR(2) NULL DEFAULT NULL,
  `short_name` VARCHAR(80) NOT NULL,
  `name` VARCHAR(80) NOT NULL,
  `iso3` CHAR(3) NULL DEFAULT NULL,
  `numcode` VARCHAR(6) NULL DEFAULT NULL,
  `calling_code` VARCHAR(8) NULL DEFAULT NULL,
  `latitude` DOUBLE NULL DEFAULT NULL,
  `longitude` DOUBLE NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `division`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `division` ;

CREATE TABLE IF NOT EXISTS `division` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL DEFAULT NULL,
  `short_name` VARCHAR(10) NULL DEFAULT NULL,
  `libelle` VARCHAR(45) NULL DEFAULT NULL,
  `code` VARCHAR(45) NULL DEFAULT NULL,
  `country_id` INT(10) UNSIGNED NULL DEFAULT NULL,
  `latitude` DOUBLE NULL DEFAULT NULL,
  `longitude` DOUBLE NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_division_country_idx` (`country_id` ASC),
  CONSTRAINT `fk_division_country`
    FOREIGN KEY (`country_id`)
    REFERENCES `country` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `city`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `city` ;

CREATE TABLE IF NOT EXISTS `city` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(128) NOT NULL,
  `libelle` VARCHAR(128) NULL DEFAULT NULL,
  `code` VARCHAR(45) NULL DEFAULT NULL,
  `division_id` INT(10) UNSIGNED NULL DEFAULT NULL,
  `country_id` INT(10) UNSIGNED NULL DEFAULT NULL,
  `latitude` DOUBLE NULL DEFAULT NULL,
  `longitude` DOUBLE NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_city_division_id_idx` (`division_id` ASC),
  INDEX `fk_city_country_idx` (`country_id` ASC),
  CONSTRAINT `fk_city_country`
    FOREIGN KEY (`country_id`)
    REFERENCES `country` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_city_division_id`
    FOREIGN KEY (`division_id`)
    REFERENCES `division` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `address`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `address` ;

CREATE TABLE IF NOT EXISTS `address` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `street_no` VARCHAR(10) NULL DEFAULT NULL,
  `street_type` VARCHAR(25) NULL DEFAULT NULL,
  `street_name` VARCHAR(128) NULL DEFAULT NULL,
  `floor` VARCHAR(128) NULL DEFAULT NULL,
  `door` VARCHAR(128) NULL DEFAULT NULL,
  `apartment` VARCHAR(128) NULL DEFAULT NULL,
  `building` VARCHAR(128) NULL DEFAULT NULL,
  `city_id` INT(10) UNSIGNED NULL DEFAULT NULL,
  `division_id` INT(10) UNSIGNED NULL DEFAULT NULL,
  `country_id` INT(10) UNSIGNED NULL DEFAULT NULL,
  `longitude` DOUBLE NULL DEFAULT NULL,
  `latitude` DOUBLE NULL DEFAULT NULL,
  `timezone` VARCHAR(128) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_address_city_idx` (`city_id` ASC),
  INDEX `fk_address_division_idx` (`division_id` ASC),
  INDEX `fk_address_country_idx` (`country_id` ASC),
  CONSTRAINT `fk_address_city`
    FOREIGN KEY (`city_id`)
    REFERENCES `city` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_address_country`
    FOREIGN KEY (`country_id`)
    REFERENCES `country` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_address_division`
    FOREIGN KEY (`division_id`)
    REFERENCES `division` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `school`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `school` ;

CREATE TABLE IF NOT EXISTS `school` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NULL DEFAULT NULL,
  `next_name` VARCHAR(45) NULL DEFAULT NULL,
  `short_name` TEXT NULL DEFAULT NULL,
  `logo` VARCHAR(80) NULL DEFAULT NULL,
  `describe` TEXT NULL DEFAULT NULL,
  `website` TEXT NULL DEFAULT NULL,
  `programme` TEXT NULL DEFAULT NULL,
  `background` VARCHAR(80) NULL DEFAULT NULL,
  `phone` VARCHAR(45) NULL DEFAULT NULL,
  `contact` VARCHAR(45) NULL DEFAULT NULL,
  `contact_id` INT(10) UNSIGNED NULL DEFAULT NULL,
  `address_id` INT(10) UNSIGNED NULL DEFAULT NULL,
  `deleted_date` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_school_1_idx` (`contact_id` ASC),
  CONSTRAINT `fk_school_1`
    FOREIGN KEY (`contact_id`)
    REFERENCES `user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `user` ;

CREATE TABLE IF NOT EXISTS `user` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `firstname` VARCHAR(128) NULL DEFAULT NULL,
  `lastname` VARCHAR(128) NULL DEFAULT NULL,
  `status` TEXT NULL DEFAULT NULL,
  `email` VARCHAR(128) NOT NULL,
  `password` VARCHAR(128) NULL DEFAULT NULL,
  `new_password` VARCHAR(128) NULL DEFAULT NULL,
  `birth_date` DATETIME NULL DEFAULT NULL,
  `position` VARCHAR(255) NULL DEFAULT NULL,
  `school_id` INT(10) UNSIGNED NULL DEFAULT NULL,
  `interest` TEXT NULL DEFAULT NULL,
  `gender` ENUM('f','m') NULL DEFAULT NULL,
  `nationality` INT(10) UNSIGNED NULL DEFAULT NULL,
  `origin` INT(10) UNSIGNED NULL DEFAULT NULL,
  `avatar` VARCHAR(255) NULL DEFAULT NULL,
  `has_email_notifier` TINYINT(1) NOT NULL DEFAULT '1',
  `deleted_date` DATETIME NULL DEFAULT NULL,
  `sis` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_user_1_idx` (`school_id` ASC),
  CONSTRAINT `fk_user_1`
    FOREIGN KEY (`school_id`)
    REFERENCES `school` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `program`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `program` ;

CREATE TABLE IF NOT EXISTS `program` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NULL DEFAULT NULL,
  `school_id` INT(10) UNSIGNED NOT NULL,
  `level` ENUM('emba','mba') NULL DEFAULT NULL,
  `sis` VARCHAR(45) NULL DEFAULT NULL,
  `year` VARCHAR(10) NULL DEFAULT NULL,
  `deleted_date` DATETIME NULL DEFAULT NULL,
  `created_date` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_program_1_idx` (`school_id` ASC),
  CONSTRAINT `fk_program_1`
    FOREIGN KEY (`school_id`)
    REFERENCES `school` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `course`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `course` ;

CREATE TABLE IF NOT EXISTS `course` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(255) NULL DEFAULT NULL,
  `creator_id` INT(10) UNSIGNED NOT NULL,
  `nb_module` INT(11) NULL DEFAULT NULL,
  `abstract` TEXT NULL DEFAULT NULL,
  `description` TEXT NULL DEFAULT NULL,
  `objectives` TEXT NULL DEFAULT NULL,
  `teaching` TEXT NULL DEFAULT NULL,
  `attendance` TEXT NULL DEFAULT NULL,
  `duration` VARCHAR(128) NULL DEFAULT NULL,
  `notes` TEXT NULL DEFAULT NULL,
  `learning_outcomes` TEXT NULL DEFAULT NULL,
  `deleted_date` DATETIME NULL DEFAULT NULL,
  `updated_date` DATETIME NULL DEFAULT NULL,
  `created_date` DATETIME NULL DEFAULT NULL,
  `version` INT(11) NULL DEFAULT NULL,
  `picture` VARCHAR(80) NULL DEFAULT NULL,
  `video_link` TEXT NULL DEFAULT NULL,
  `video_token` TEXT NULL DEFAULT NULL,
  `program_id` INT(10) UNSIGNED NOT NULL,
  `sis` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_course_1_idx` (`creator_id` ASC),
  INDEX `fk_course_2_idx` (`program_id` ASC),
  CONSTRAINT `fk_course_1`
    FOREIGN KEY (`creator_id`)
    REFERENCES `user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_course_2`
    FOREIGN KEY (`program_id`)
    REFERENCES `program` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `grading_policy`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `grading_policy` ;

CREATE TABLE IF NOT EXISTS `grading_policy` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` TEXT NULL DEFAULT NULL,
  `grade` DOUBLE NULL DEFAULT NULL,
  `type` ENUM('LC','WG','CP','IA') NULL DEFAULT NULL,
  `tpl` TINYINT(1) NOT NULL DEFAULT '0',
  `course_id` INT(10) UNSIGNED NULL DEFAULT NULL,
  `mandatory` TINYINT(1) NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  INDEX `fk_grading_policy_1_idx` (`course_id` ASC),
  CONSTRAINT `fk_grading_policy_1`
    FOREIGN KEY (`course_id`)
    REFERENCES `course` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `item`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `item` ;

CREATE TABLE IF NOT EXISTS `item` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `course_id` INT(10) UNSIGNED NOT NULL,
  `grading_policy_id` INT(10) UNSIGNED NULL DEFAULT NULL,
  `title` VARCHAR(512) NULL DEFAULT NULL,
  `describe` TEXT NULL DEFAULT NULL,
  `duration` VARCHAR(512) NULL DEFAULT NULL,
  `type` ENUM('LC', 'WG', 'CP', 'IA', 'DOC', 'TXT', 'POLL', 'MOD', 'DISC', 'CHAT', 'EQCQ') NOT NULL,
  `set_id` INT UNSIGNED NULL,
  `parent_id` INT UNSIGNED NULL DEFAULT NULL,
  `order_id` INT UNSIGNED NULL DEFAULT NULL,
  `has_submission` TINYINT(1) NOT NULL DEFAULT 1,
  `start` DATETIME NULL,
  `end` DATETIME NULL,
  `cut_off` DATETIME NULL,
  `is_graded` TINYINT(1) NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  INDEX `fk_item_1_idx` (`course_id` ASC),
  INDEX `fk_item_4_idx` (`grading_policy_id` ASC),
  INDEX `fk_item_2_idx` (`parent_id` ASC),
  INDEX `fk_item_3_idx` (`order_id` ASC),
  CONSTRAINT `fk_item_1`
    FOREIGN KEY (`course_id`)
    REFERENCES `course` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_item_4`
    FOREIGN KEY (`grading_policy_id`)
    REFERENCES `grading_policy` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_item_2`
    FOREIGN KEY (`parent_id`)
    REFERENCES `item` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_item_3`
    FOREIGN KEY (`order_id`)
    REFERENCES `item` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `set`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `set` ;

CREATE TABLE IF NOT EXISTS `set` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `uid` VARCHAR(80) NULL,
  `name` VARCHAR(80) NULL,
  `course_id` INT UNSIGNED NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_set_1_idx` (`course_id` ASC),
  CONSTRAINT `fk_set_1`
    FOREIGN KEY (`course_id`)
    REFERENCES `course` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `questionnaire`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `questionnaire` ;

CREATE TABLE IF NOT EXISTS `questionnaire` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `item_id` INT(10) UNSIGNED NULL DEFAULT NULL,
  `created_date` DATETIME NOT NULL,
  `max_duration` INT(11) NOT NULL DEFAULT '30',
  `max_time` INT(11) NOT NULL DEFAULT '2',
  `set_id` INT UNSIGNED NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_questionnaire_1_idx` (`item_id` ASC),
  INDEX `fk_questionnaire_2_idx` (`set_id` ASC),
  CONSTRAINT `fk_questionnaire_1`
    FOREIGN KEY (`item_id`)
    REFERENCES `item` (`id`)
    ON DELETE SET NULL
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_questionnaire_2`
    FOREIGN KEY (`set_id`)
    REFERENCES `set` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `submission`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `submission` ;

CREATE TABLE IF NOT EXISTS `submission` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `item_id` INT UNSIGNED NULL,
  `group_id` INT NULL,
  `group_name` VARCHAR(45) NULL,
  `submit_date` DATETIME NULL,
  `is_graded` TINYINT(1) NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  INDEX `item_id_idx` (`item_id` ASC),
  CONSTRAINT `item_id`
    FOREIGN KEY (`item_id`)
    REFERENCES `item` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `questionnaire_user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `questionnaire_user` ;

CREATE TABLE IF NOT EXISTS `questionnaire_user` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `user_id` INT(10) UNSIGNED NOT NULL,
  `questionnaire_id` INT(10) UNSIGNED NOT NULL,
  `submission_id` INT(10) UNSIGNED NOT NULL,
  `state` INT(11) NULL DEFAULT NULL,
  `created_date` DATETIME NOT NULL,
  `end_date` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_questionnaire_user_1_idx` (`user_id` ASC),
  INDEX `fk_questionnaire_user_2_idx` (`questionnaire_id` ASC),
  INDEX `fk_questionnaire_user_3_idx` (`submission_id` ASC),
  CONSTRAINT `fk_questionnaire_user_1`
    FOREIGN KEY (`user_id`)
    REFERENCES `user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_questionnaire_user_2`
    FOREIGN KEY (`questionnaire_id`)
    REFERENCES `questionnaire` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_questionnaire_user_3`
    FOREIGN KEY (`submission_id`)
    REFERENCES `submission` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `scale`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `scale` ;

CREATE TABLE IF NOT EXISTS `scale` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `value` INT(11) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `dimension`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dimension` ;

CREATE TABLE IF NOT EXISTS `dimension` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` ENUM('EQ','CQ') NOT NULL,
  `describe` TEXT NOT NULL,
  `deleted_date` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `component`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `component` ;

CREATE TABLE IF NOT EXISTS `component` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `dimension_id` INT(10) UNSIGNED NOT NULL,
  `describe` TEXT NULL DEFAULT NULL,
  `deleted_date` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_component_1_idx` (`dimension_id` ASC),
  CONSTRAINT `fk_component_1`
    FOREIGN KEY (`dimension_id`)
    REFERENCES `dimension` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `question`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `question` ;

CREATE TABLE IF NOT EXISTS `question` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `text` TEXT NULL DEFAULT NULL,
  `component_id` INT(10) UNSIGNED NULL DEFAULT NULL,
  `created_date` DATETIME NULL DEFAULT NULL,
  `deleted_date` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_question_1_idx` (`component_id` ASC),
  CONSTRAINT `fk_question_1`
    FOREIGN KEY (`component_id`)
    REFERENCES `component` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `questionnaire_question`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `questionnaire_question` ;

CREATE TABLE IF NOT EXISTS `questionnaire_question` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `question_id` INT(10) UNSIGNED NOT NULL,
  `questionnaire_id` INT(10) UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_questionnaire_1_idx` (`question_id` ASC),
  INDEX `fk_questionnaire_question_1_idx` (`questionnaire_id` ASC),
  CONSTRAINT `fk_questionnaire_question_1`
    FOREIGN KEY (`questionnaire_id`)
    REFERENCES `questionnaire` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_questionnaire_question_2`
    FOREIGN KEY (`question_id`)
    REFERENCES `question` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `answer`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `answer` ;

CREATE TABLE IF NOT EXISTS `answer` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `questionnaire_user_id` INT(10) UNSIGNED NOT NULL,
  `questionnaire_question_id` INT(10) UNSIGNED NOT NULL,
  `question_id` INT(10) UNSIGNED NOT NULL,
  `peer_id` INT(10) UNSIGNED NOT NULL,
  `scale_id` INT(10) UNSIGNED NOT NULL,
  `type` ENUM('SELF','PEER') NULL DEFAULT NULL,
  `created_date` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `uq_answer` (`questionnaire_user_id` ASC, `questionnaire_question_id` ASC, `peer_id` ASC),
  INDEX `fk_answer_1_idx` (`questionnaire_user_id` ASC),
  INDEX `fk_answer_2_idx` (`scale_id` ASC),
  INDEX `fk_answer_4_idx` (`questionnaire_question_id` ASC),
  INDEX `fk_answer_3_idx` (`question_id` ASC),
  INDEX `fk_answer_5_idx` (`peer_id` ASC),
  CONSTRAINT `fk_answer_1`
    FOREIGN KEY (`questionnaire_user_id`)
    REFERENCES `questionnaire_user` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_answer_2`
    FOREIGN KEY (`scale_id`)
    REFERENCES `scale` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_answer_3`
    FOREIGN KEY (`question_id`)
    REFERENCES `question` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_answer_4`
    FOREIGN KEY (`questionnaire_question_id`)
    REFERENCES `questionnaire_question` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_answer_5`
    FOREIGN KEY (`peer_id`)
    REFERENCES `user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `changelog`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `changelog` ;

CREATE TABLE IF NOT EXISTS `changelog` (
  `change_number` BIGINT(20) NOT NULL,
  `delta_set` VARCHAR(10) NOT NULL,
  `start_dt` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `complete_dt` TIMESTAMP NULL DEFAULT NULL,
  `applied_by` VARCHAR(100) NOT NULL,
  `description` VARCHAR(500) NOT NULL)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `component_scale`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `component_scale` ;

CREATE TABLE IF NOT EXISTS `component_scale` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `component_id` INT(10) UNSIGNED NOT NULL,
  `min` INT(11) NOT NULL,
  `max` INT(11) NOT NULL,
  `describe` TEXT NOT NULL,
  `recommandation` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_component_scale_1_idx` (`component_id` ASC),
  CONSTRAINT `fk_component_scale_1`
    FOREIGN KEY (`component_id`)
    REFERENCES `component` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `connection`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `connection` ;

CREATE TABLE IF NOT EXISTS `connection` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `user_id` INT(10) UNSIGNED NOT NULL,
  `token` VARCHAR(80) NOT NULL,
  `end` DATETIME NOT NULL,
  `start` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_connection_2_idx` (`user_id` ASC),
  CONSTRAINT `fk_connection_2`
    FOREIGN KEY (`user_id`)
    REFERENCES `user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `contact`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `contact` ;

CREATE TABLE IF NOT EXISTS `contact` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `user_id` INT(10) UNSIGNED NOT NULL,
  `contact_id` INT(10) UNSIGNED NOT NULL,
  `request_date` DATETIME NULL DEFAULT NULL,
  `deleted_date` DATETIME NULL DEFAULT NULL,
  `accepted_date` DATETIME NULL DEFAULT NULL,
  `deleted` TINYINT(1) NOT NULL DEFAULT 0,
  `accepted` TINYINT(1) NOT NULL DEFAULT 0,
  `requested` TINYINT(1) NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `unoque_cantact` (`user_id` ASC, `contact_id` ASC),
  INDEX `fk_contact_1_idx` (`user_id` ASC),
  INDEX `fk_contact_2_idx` (`contact_id` ASC),
  CONSTRAINT `fk_contact_1`
    FOREIGN KEY (`user_id`)
    REFERENCES `user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_contact_2`
    FOREIGN KEY (`contact_id`)
    REFERENCES `user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `conversation`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `conversation` ;

CREATE TABLE IF NOT EXISTS `conversation` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NULL DEFAULT 'Chat',
  `type` INT NULL DEFAULT NULL,
  `submission_id` INT UNSIGNED NULL,
  `created_date` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_conversation_1_idx` (`submission_id` ASC),
  CONSTRAINT `fk_conversation_1`
    FOREIGN KEY (`submission_id`)
    REFERENCES `submission` (`id`)
    ON DELETE SET NULL
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `conversation_user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `conversation_user` ;

CREATE TABLE IF NOT EXISTS `conversation_user` (
  `conversation_id` INT(10) UNSIGNED NOT NULL,
  `user_id` INT(10) UNSIGNED NOT NULL,
  PRIMARY KEY (`conversation_id`, `user_id`),
  INDEX `fk_conversation_user_2_idx` (`user_id` ASC),
  CONSTRAINT `fk_conversation_user_1`
    FOREIGN KEY (`conversation_id`)
    REFERENCES `conversation` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_conversation_user_2`
    FOREIGN KEY (`user_id`)
    REFERENCES `user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `course_user_relation`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `course_user_relation` ;

CREATE TABLE IF NOT EXISTS `course_user_relation` (
  `user_id` INT(10) UNSIGNED NOT NULL,
  `course_id` INT(10) UNSIGNED NOT NULL,
  PRIMARY KEY (`user_id`, `course_id`),
  INDEX `fk_course_user_relation_1_idx` (`course_id` ASC),
  CONSTRAINT `fk_course_user_relation_1`
    FOREIGN KEY (`course_id`)
    REFERENCES `course` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_course_user_relation_2`
    FOREIGN KEY (`user_id`)
    REFERENCES `user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `dimension_scale`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dimension_scale` ;

CREATE TABLE IF NOT EXISTS `dimension_scale` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `dimension_id` INT(10) UNSIGNED NOT NULL,
  `min` INT(11) NOT NULL,
  `max` INT(11) NOT NULL,
  `describe` TEXT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_dimension_scale_1_idx` (`dimension_id` ASC),
  CONSTRAINT `fk_dimension_scale_1`
    FOREIGN KEY (`dimension_id`)
    REFERENCES `dimension` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `library`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `library` ;

CREATE TABLE IF NOT EXISTS `library` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NULL DEFAULT NULL,
  `link` VARCHAR(255) NULL DEFAULT NULL,
  `token` VARCHAR(80) NULL DEFAULT NULL,
  `type` VARCHAR(255) NULL,
  `created_date` DATETIME NULL DEFAULT NULL,
  `deleted_date` DATETIME NULL DEFAULT NULL,
  `updated_date` DATETIME NULL DEFAULT NULL,
  `folder_id` INT UNSIGNED NULL,
  `owner_id` INT UNSIGNED NULL,
  `box_id` VARCHAR(255) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_library_1_idx` (`folder_id` ASC),
  INDEX `fk_library_2_idx` (`owner_id` ASC),
  CONSTRAINT `fk_library_1`
    FOREIGN KEY (`folder_id`)
    REFERENCES `library` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_library_2`
    FOREIGN KEY (`owner_id`)
    REFERENCES `user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `document`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `document` ;

CREATE TABLE IF NOT EXISTS `document` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `item_id` INT(10) UNSIGNED NULL,
  `submission_id` INT UNSIGNED NULL,
  `library_id` INT UNSIGNED NOT NULL,
  `created_date` DATETIME NULL DEFAULT NULL,
  `deleted_date` DATETIME NULL DEFAULT NULL,
  `updated_date` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `item_id_UNIQUE` (`item_id` ASC),
  INDEX `fk_document_1_idx` (`item_id` ASC),
  INDEX `fk_document_2_idx` (`library_id` ASC),
  INDEX `fk_document_3_idx` (`submission_id` ASC),
  CONSTRAINT `fk_document_1`
    FOREIGN KEY (`item_id`)
    REFERENCES `item` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_document_2`
    FOREIGN KEY (`library_id`)
    REFERENCES `library` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_document_3`
    FOREIGN KEY (`submission_id`)
    REFERENCES `submission` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `event`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `event` ;

CREATE TABLE IF NOT EXISTS `event` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `user_id` INT(11) NULL DEFAULT NULL,
  `source` TEXT NULL DEFAULT NULL,
  `date` DATETIME NULL DEFAULT NULL,
  `event` VARCHAR(255) NULL DEFAULT NULL,
  `object` TEXT NULL DEFAULT NULL,
  `target` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `event_comment`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `event_comment` ;

CREATE TABLE IF NOT EXISTS `event_comment` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `content` TEXT NULL DEFAULT NULL,
  `user_id` INT(10) UNSIGNED NULL DEFAULT NULL,
  `event_id` INT(10) UNSIGNED NULL DEFAULT NULL,
  `created_date` DATETIME NULL DEFAULT NULL,
  `deleted_date` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_feed_comment_1_idx` (`user_id` ASC),
  INDEX `fk_feed_comment_2_idx` (`event_id` ASC),
  CONSTRAINT `fk_feed_comment_1`
    FOREIGN KEY (`user_id`)
    REFERENCES `user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_feed_comment_2`
    FOREIGN KEY (`event_id`)
    REFERENCES `event` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `event_user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `event_user` ;

CREATE TABLE IF NOT EXISTS `event_user` (
  `event_id` INT(10) UNSIGNED NOT NULL,
  `user_id` INT(10) UNSIGNED NOT NULL,
  `read_date` DATETIME NULL DEFAULT NULL,
  `view_date` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`user_id`, `event_id`),
  INDEX `fk_notication_user_1_idx` (`event_id` ASC),
  CONSTRAINT `fk_notication_user_1`
    FOREIGN KEY (`event_id`)
    REFERENCES `event` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_notication_user_2`
    FOREIGN KEY (`user_id`)
    REFERENCES `user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `faq`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `faq` ;

CREATE TABLE IF NOT EXISTS `faq` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `ask` TEXT NULL DEFAULT NULL,
  `answer` TEXT NULL DEFAULT NULL,
  `course_id` INT(10) UNSIGNED NOT NULL,
  `created_date` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_faq_1_idx` (`course_id` ASC),
  CONSTRAINT `fk_faq_1`
    FOREIGN KEY (`course_id`)
    REFERENCES `course` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `feed`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `feed` ;

CREATE TABLE IF NOT EXISTS `feed` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `content` TEXT NULL DEFAULT NULL,
  `user_id` INT(10) UNSIGNED NULL DEFAULT NULL,
  `link` TEXT NULL DEFAULT NULL,
  `video` VARCHAR(80) NULL DEFAULT NULL,
  `picture` VARCHAR(512) NULL DEFAULT NULL,
  `name_picture` VARCHAR(255) NULL DEFAULT NULL,
  `document` VARCHAR(80) NULL DEFAULT NULL,
  `name_document` VARCHAR(255) NULL DEFAULT NULL,
  `link_title` VARCHAR(512) NULL DEFAULT NULL,
  `link_desc` TEXT NULL DEFAULT NULL,
  `created_date` DATETIME NULL DEFAULT NULL,
  `deleted_date` DATETIME NULL DEFAULT NULL,
  `type` ENUM('social','academic') NOT NULL DEFAULT 'social',
  PRIMARY KEY (`id`),
  INDEX `fk_feed_1_idx` (`user_id` ASC),
  CONSTRAINT `fk_feed_1`
    FOREIGN KEY (`user_id`)
    REFERENCES `user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `grading`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `grading` ;

CREATE TABLE IF NOT EXISTS `grading` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `letter` VARCHAR(3) NULL DEFAULT NULL,
  `min` INT(11) NULL DEFAULT NULL,
  `max` INT(11) NULL DEFAULT NULL,
  `grade` DOUBLE NULL DEFAULT NULL,
  `description` TEXT NULL DEFAULT NULL,
  `tpl` TINYINT(1) NOT NULL DEFAULT '0',
  `school_id` INT(10) UNSIGNED NULL DEFAULT NULL,
  `program_id` INT(10) UNSIGNED NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_grading_1_idx` (`school_id` ASC),
  CONSTRAINT `fk_grading_1`
    FOREIGN KEY (`school_id`)
    REFERENCES `school` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `grading_policy_grade`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `grading_policy_grade` ;

CREATE TABLE IF NOT EXISTS `grading_policy_grade` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `grading_policy_id` INT(10) UNSIGNED NULL DEFAULT NULL,
  `grade` INT(10) UNSIGNED NULL DEFAULT NULL,
  `user_id` INT(10) UNSIGNED NULL DEFAULT NULL,
  `created_date` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `unique` (`grading_policy_id` ASC, `user_id` ASC),
  INDEX `fk_item_grading_20_idx` (`grading_policy_id` ASC),
  INDEX `fk_grading_policy_grade_1_idx` USING BTREE (`user_id` ASC),
  CONSTRAINT `fk_grading_policy_grade_1`
    FOREIGN KEY (`user_id`)
    REFERENCES `user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_item_grading_20`
    FOREIGN KEY (`grading_policy_id`)
    REFERENCES `grading_policy` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `grading_policy_grade_comment`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `grading_policy_grade_comment` ;

CREATE TABLE IF NOT EXISTS `grading_policy_grade_comment` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `text` TEXT NULL DEFAULT NULL,
  `user_id` INT(10) UNSIGNED NOT NULL,
  `grading_policy_grade_id` INT(10) UNSIGNED NOT NULL,
  `created_date` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_item_assignment_comment_1_idx` (`user_id` ASC),
  INDEX `fk_item_assignment_100_idx` (`grading_policy_grade_id` ASC),
  CONSTRAINT `fk_item_assignment_100`
    FOREIGN KEY (`grading_policy_grade_id`)
    REFERENCES `grading_policy_grade` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_item_assignment_comment_10`
    FOREIGN KEY (`user_id`)
    REFERENCES `user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `guidelines`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `guidelines` ;

CREATE TABLE IF NOT EXISTS `guidelines` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `state` VARCHAR(255) NULL DEFAULT NULL,
  `data` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `guidelines_view`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `guidelines_view` ;

CREATE TABLE IF NOT EXISTS `guidelines_view` (
  `state` VARCHAR(255) NULL DEFAULT NULL,
  `user_id` INT(10) UNSIGNED NULL DEFAULT NULL,
  UNIQUE INDEX `index1` (`state` ASC, `user_id` ASC),
  INDEX `fk_guidelines_view_1_idx` (`user_id` ASC),
  CONSTRAINT `fk_guidelines_view_1`
    FOREIGN KEY (`user_id`)
    REFERENCES `user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `text_editor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `text_editor` ;

CREATE TABLE IF NOT EXISTS `text_editor` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL DEFAULT 'Text Editor',
  `text` TEXT NOT NULL,
  `submission_id` INT(10) UNSIGNED NULL DEFAULT NULL,
  `submit_date` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_assignment_1_idx` (`submission_id` ASC),
  CONSTRAINT `fk_assignment_1`
    FOREIGN KEY (`submission_id`)
    REFERENCES `submission` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `submission_comments`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `submission_comments` ;

CREATE TABLE IF NOT EXISTS `submission_comments` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `text` TEXT NULL DEFAULT NULL,
  `audio` VARCHAR(80) NULL DEFAULT NULL,
  `user_id` INT(10) UNSIGNED NOT NULL,
  `submission_id` INT(10) UNSIGNED NOT NULL,
  `file_token` VARCHAR(80) NULL DEFAULT NULL,
  `file_name` VARCHAR(255) NULL DEFAULT NULL,
  `created_date` DATETIME NULL DEFAULT NULL,
  `read_date` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_submission_comment_10_idx` (`submission_id` ASC),
  INDEX `fk_submission_comment_1_idx` (`user_id` ASC),
  CONSTRAINT `fk_submission_comment_10`
    FOREIGN KEY (`submission_id`)
    REFERENCES `text_editor` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_submission_comment_1`
    FOREIGN KEY (`user_id`)
    REFERENCES `user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `item_grading`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `item_grading` ;

CREATE TABLE IF NOT EXISTS `item_grading` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `item_prog_user_id` INT(10) UNSIGNED NULL DEFAULT NULL,
  `grade` INT(10) UNSIGNED NULL DEFAULT NULL,
  `created_date` DATETIME NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `material_document`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `material_document` ;

CREATE TABLE IF NOT EXISTS `material_document` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `course_id` INT(10) UNSIGNED NOT NULL,
  `type` VARCHAR(100) NULL DEFAULT NULL,
  `title` VARCHAR(45) NULL DEFAULT NULL,
  `author` VARCHAR(45) NULL DEFAULT NULL,
  `link` VARCHAR(512) NULL DEFAULT NULL,
  `source` TEXT NULL DEFAULT NULL,
  `token` VARCHAR(80) NULL DEFAULT NULL,
  `description` TEXT NULL DEFAULT NULL,
  `date` DATE NULL DEFAULT NULL,
  `created_date` DATETIME NULL DEFAULT NULL,
  `deleted_date` DATETIME NULL DEFAULT NULL,
  `updated_date` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_mterials_documents_1_idx` (`course_id` ASC),
  CONSTRAINT `fk_mterials_documents_1`
    FOREIGN KEY (`course_id`)
    REFERENCES `course` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `item_material_document_relation`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `item_material_document_relation` ;

CREATE TABLE IF NOT EXISTS `item_material_document_relation` (
  `item_id` INT(10) UNSIGNED NOT NULL,
  `material_document_id` INT(10) UNSIGNED NOT NULL,
  PRIMARY KEY (`item_id`, `material_document_id`),
  INDEX `fk_item_material_document_relation_2_idx` (`material_document_id` ASC),
  CONSTRAINT `fk_item_material_document_relation_1`
    FOREIGN KEY (`item_id`)
    REFERENCES `item` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_item_material_document_relation_2`
    FOREIGN KEY (`material_document_id`)
    REFERENCES `material_document` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `language`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `language` ;

CREATE TABLE IF NOT EXISTS `language` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `libelle` VARCHAR(128) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `language_level`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `language_level` ;

CREATE TABLE IF NOT EXISTS `language_level` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `level` VARCHAR(256) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `like`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `like` ;

CREATE TABLE IF NOT EXISTS `like` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `is_like` TINYINT(1) NOT NULL DEFAULT '1',
  `user_id` INT(10) UNSIGNED NOT NULL,
  `event_id` INT(10) UNSIGNED NOT NULL,
  `created_date` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_like_1_idx` (`user_id` ASC),
  INDEX `fk_like_2_idx` (`event_id` ASC),
  CONSTRAINT `fk_like_1`
    FOREIGN KEY (`user_id`)
    REFERENCES `user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_like_2`
    FOREIGN KEY (`event_id`)
    REFERENCES `event` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mail`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mail` ;

CREATE TABLE IF NOT EXISTS `mail` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `mail_group_id` VARCHAR(255) NULL DEFAULT NULL,
  `suject` VARCHAR(512) NULL DEFAULT NULL,
  `content` TEXT NULL DEFAULT NULL,
  `created_date` DATETIME NOT NULL,
  `draft` TINYINT(1) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mail_doc`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mail_doc` ;

CREATE TABLE IF NOT EXISTS `mail_doc` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `token` VARCHAR(100) NOT NULL,
  `mail_id` INT(10) UNSIGNED NOT NULL,
  `created_date` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_maildoc_1_idx` (`mail_id` ASC),
  CONSTRAINT `fk_mail_doc_1`
    FOREIGN KEY (`mail_id`)
    REFERENCES `mail` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mail_receiver`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mail_receiver` ;

CREATE TABLE IF NOT EXISTS `mail_receiver` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `type` ENUM('cc','cci','to','from') NOT NULL,
  `user_id` INT(10) UNSIGNED NOT NULL,
  `mail_id` INT(10) UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_message_receiver_1_idx` (`user_id` ASC),
  INDEX `fk_message_receiver_2_idx` (`mail_id` ASC),
  CONSTRAINT `fk_message_receiver_1`
    FOREIGN KEY (`user_id`)
    REFERENCES `user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_message_receiver_2`
    FOREIGN KEY (`mail_id`)
    REFERENCES `mail` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mail_user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mail_user` ;

CREATE TABLE IF NOT EXISTS `mail_user` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `mail_id` INT(10) UNSIGNED NULL DEFAULT NULL,
  `user_id` INT(10) UNSIGNED NULL DEFAULT NULL,
  `mail_group_id` VARCHAR(255) NULL DEFAULT NULL,
  `created_date` DATETIME NOT NULL,
  `deleted_date` DATETIME NULL DEFAULT NULL,
  `read_date` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_message_user_1_idx` (`mail_id` ASC),
  INDEX `fk_message_user_2_idx` (`user_id` ASC),
  CONSTRAINT `fk_mail_user_1`
    FOREIGN KEY (`mail_id`)
    REFERENCES `mail` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_mail_user_2`
    FOREIGN KEY (`user_id`)
    REFERENCES `user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `message`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `message` ;

CREATE TABLE IF NOT EXISTS `message` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(255) NULL DEFAULT NULL,
  `text` TEXT NULL DEFAULT NULL,
  `token` VARCHAR(80) NULL DEFAULT NULL,
  `is_draft` TINYINT(1) NOT NULL DEFAULT '0',
  `type` INT(11) NULL DEFAULT NULL,
  `conversation_id` INT(10) UNSIGNED NOT NULL,
  `created_date` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_message_1_idx` (`conversation_id` ASC),
  CONSTRAINT `fk_message_1`
    FOREIGN KEY (`conversation_id`)
    REFERENCES `conversation` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `message_doc`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `message_doc` ;

CREATE TABLE IF NOT EXISTS `message_doc` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `token` VARCHAR(100) NOT NULL,
  `name` VARCHAR(255) NULL DEFAULT NULL,
  `message_id` INT(10) UNSIGNED NOT NULL,
  `created_date` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_message_doc_1_idx` (`message_id` ASC),
  CONSTRAINT `fk_message_doc_1`
    FOREIGN KEY (`message_id`)
    REFERENCES `message` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `message_user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `message_user` ;

CREATE TABLE IF NOT EXISTS `message_user` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `message_id` INT(10) UNSIGNED NOT NULL,
  `conversation_id` INT(10) UNSIGNED NOT NULL,
  `from_id` INT(10) UNSIGNED NOT NULL,
  `user_id` INT(10) UNSIGNED NOT NULL,
  `read_date` DATETIME NULL DEFAULT NULL,
  `deleted_date` DATETIME NULL DEFAULT NULL,
  `created_date` DATETIME NOT NULL,
  `type` ENUM('R','S','RS') NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `unique_message_user` (`message_id` ASC, `user_id` ASC),
  INDEX `fk_message_user_1_idx` (`message_id` ASC),
  INDEX `fk_message_user_2_idx` (`conversation_id` ASC),
  INDEX `fk_message_user_3_idx` (`from_id` ASC),
  INDEX `fk_message_user_4_idx` (`user_id` ASC),
  CONSTRAINT `fk_message_user_1`
    FOREIGN KEY (`message_id`)
    REFERENCES `message` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_message_user_2`
    FOREIGN KEY (`conversation_id`)
    REFERENCES `conversation` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_message_user_3`
    FOREIGN KEY (`from_id`)
    REFERENCES `user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_message_user_4`
    FOREIGN KEY (`user_id`)
    REFERENCES `user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `permission`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `permission` ;

CREATE TABLE IF NOT EXISTS `permission` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `libelle` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `libelle_UNIQUE` (`libelle` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `poll`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `poll` ;

CREATE TABLE IF NOT EXISTS `poll` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(128) NULL DEFAULT NULL,
  `expiration_date` DATETIME NULL,
  `time_limit` INT NULL,
  `item_id` INT UNSIGNED NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_poll_1_idx` (`item_id` ASC),
  CONSTRAINT `fk_poll_1`
    FOREIGN KEY (`item_id`)
    REFERENCES `item` (`id`)
    ON DELETE SET NULL
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `sub_quiz`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sub_quiz` ;

CREATE TABLE IF NOT EXISTS `sub_quiz` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `poll_id` INT(10) UNSIGNED NOT NULL,
  `start_date` DATETIME NULL,
  `end_date` DATETIME NULL,
  `user_id` INT(10) UNSIGNED NOT NULL,
  `submission_id` INT UNSIGNED NULL,
  `grade` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_poll_answer_2_idx` (`poll_id` ASC),
  INDEX `fk_poll_answer_3_idx` (`user_id` ASC),
  INDEX `fk_poll_answer_6_idx` (`submission_id` ASC),
  CONSTRAINT `fk_poll_answer_2`
    FOREIGN KEY (`poll_id`)
    REFERENCES `poll` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_poll_answer_3`
    FOREIGN KEY (`user_id`)
    REFERENCES `user` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_poll_answer_6`
    FOREIGN KEY (`submission_id`)
    REFERENCES `submission` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `sub_answer`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sub_answer` ;

CREATE TABLE IF NOT EXISTS `sub_answer` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `sub_question_id` INT(10) UNSIGNED NOT NULL,
  `bank_question_item_id` INT(10) UNSIGNED NULL DEFAULT NULL,
  `answer` TEXT NULL DEFAULT NULL,
  `date` DATE NULL DEFAULT NULL,
  `time` TIME NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_poll_answer_items_1_idx` (`sub_question_id` ASC),
  CONSTRAINT `fk_poll_answer_item_2`
    FOREIGN KEY (`sub_question_id`)
    REFERENCES `sub_quiz` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bank_question_type`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bank_question_type` ;

CREATE TABLE IF NOT EXISTS `bank_question_type` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bank_question`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bank_question` ;

CREATE TABLE IF NOT EXISTS `bank_question` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NULL,
  `question` TEXT NULL DEFAULT NULL,
  `bank_question_type_id` INT(10) UNSIGNED NOT NULL,
  `course_id` VARCHAR(45) NULL,
  `point` INT NULL,
  `older` VARCHAR(45) NULL,
  `created_date` DATETIME NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_poll_question_1_idx` (`bank_question_type_id` ASC),
  CONSTRAINT `fk_poll_question_10`
    FOREIGN KEY (`bank_question_type_id`)
    REFERENCES `bank_question_type` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `group_question`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `group_question` ;

CREATE TABLE IF NOT EXISTS `group_question` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nb` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `poll_item`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `poll_item` ;

CREATE TABLE IF NOT EXISTS `poll_item` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `poll_id` INT(10) UNSIGNED NULL DEFAULT NULL,
  `bank_question_id` INT(10) UNSIGNED NULL,
  `group_question_id` INT UNSIGNED NULL,
  `order_id` INT(10) UNSIGNED NULL DEFAULT NULL,
  `is_mandatory` TINYINT(1) NOT NULL,
  `nb_point` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_poll_question_2_idx` (`poll_id` ASC),
  INDEX `fk_poll_question_3_idx` (`order_id` ASC),
  INDEX `fk_poll_question_1_idx` (`bank_question_id` ASC),
  INDEX `fk_poll_item_1_idx` (`group_question_id` ASC),
  CONSTRAINT `fk_poll_question_1`
    FOREIGN KEY (`bank_question_id`)
    REFERENCES `bank_question` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_poll_question_2`
    FOREIGN KEY (`poll_id`)
    REFERENCES `poll` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_poll_question_3`
    FOREIGN KEY (`order_id`)
    REFERENCES `poll_item` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_poll_question_4`
    FOREIGN KEY (`group_question_id`)
    REFERENCES `group_question` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `professional_experience`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `professional_experience` ;

CREATE TABLE IF NOT EXISTS `professional_experience` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `date` DATETIME NULL DEFAULT NULL,
  `address` VARCHAR(255) NULL DEFAULT NULL,
  `logo` VARCHAR(255) NULL DEFAULT NULL,
  `title` VARCHAR(255) NULL DEFAULT NULL,
  `description` TEXT NULL DEFAULT NULL,
  `user_id` INT(10) UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_professional_experience_1_idx` (`user_id` ASC),
  CONSTRAINT `fk_professional_experience_1`
    FOREIGN KEY (`user_id`)
    REFERENCES `user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `program_user_relation`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `program_user_relation` ;

CREATE TABLE IF NOT EXISTS `program_user_relation` (
  `program_id` INT(10) UNSIGNED NOT NULL,
  `user_id` INT(10) UNSIGNED NOT NULL,
  PRIMARY KEY (`program_id`, `user_id`),
  INDEX `fk_program_user_relation_2_idx` (`user_id` ASC),
  CONSTRAINT `fk_program_user_relation_1`
    FOREIGN KEY (`program_id`)
    REFERENCES `program` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_program_user_relation_2`
    FOREIGN KEY (`user_id`)
    REFERENCES `user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `question_replace`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `question_replace` ;

CREATE TABLE IF NOT EXISTS `question_replace` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `resume`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `resume` ;

CREATE TABLE IF NOT EXISTS `resume` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `start_date` DATE NULL DEFAULT NULL,
  `end_date` DATE NULL DEFAULT NULL,
  `address` VARCHAR(255) NULL DEFAULT NULL,
  `title` VARCHAR(255) NULL DEFAULT NULL,
  `subtitle` VARCHAR(255) NULL DEFAULT NULL,
  `logo` VARCHAR(255) NULL DEFAULT NULL,
  `description` TEXT NULL DEFAULT NULL,
  `type` INT(11) NULL DEFAULT NULL,
  `user_id` INT(10) UNSIGNED NOT NULL,
  `publisher` VARCHAR(255) NULL DEFAULT NULL,
  `url` VARCHAR(512) NULL DEFAULT NULL,
  `cause` VARCHAR(255) NULL DEFAULT NULL,
  `study` VARCHAR(255) NULL DEFAULT NULL,
  `grade` VARCHAR(255) NULL DEFAULT NULL,
  `note` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_education_1_idx` (`user_id` ASC),
  CONSTRAINT `fk_education_1`
    FOREIGN KEY (`user_id`)
    REFERENCES `user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `role`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `role` ;

CREATE TABLE IF NOT EXISTS `role` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `role_permission`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `role_permission` ;

CREATE TABLE IF NOT EXISTS `role_permission` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `role_id` INT(10) UNSIGNED NOT NULL,
  `permission_id` INT(10) UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `index4` (`role_id` ASC, `permission_id` ASC),
  INDEX `fk_role_permission_1_idx` (`permission_id` ASC),
  INDEX `fk_role_permission_2_idx` (`role_id` ASC),
  CONSTRAINT `fk_role_permission_1`
    FOREIGN KEY (`permission_id`)
    REFERENCES `permission` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_role_permission_2`
    FOREIGN KEY (`role_id`)
    REFERENCES `role` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `role_relation`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `role_relation` ;

CREATE TABLE IF NOT EXISTS `role_relation` (
  `role_id` INT(10) UNSIGNED NOT NULL,
  `parent_id` INT(10) UNSIGNED NOT NULL,
  PRIMARY KEY (`role_id`, `parent_id`),
  INDEX `fk_role_relation_2_idx` (`parent_id` ASC),
  CONSTRAINT `fk_role_relation_1`
    FOREIGN KEY (`role_id`)
    REFERENCES `role` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_role_relation_2`
    FOREIGN KEY (`parent_id`)
    REFERENCES `role` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `school_picture`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `school_picture` ;

CREATE TABLE IF NOT EXISTS `school_picture` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `school_id` INT(10) UNSIGNED NULL DEFAULT NULL,
  `token` VARCHAR(80) NULL DEFAULT NULL,
  `name` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_school_picture_1_idx` (`school_id` ASC),
  CONSTRAINT `fk_school_picture_1`
    FOREIGN KEY (`school_id`)
    REFERENCES `school` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `school_video`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `school_video` ;

CREATE TABLE IF NOT EXISTS `school_video` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `token` VARCHAR(80) NULL DEFAULT NULL,
  `url` TEXT NULL DEFAULT NULL,
  `name` VARCHAR(255) NULL DEFAULT NULL,
  `school_id` INT(10) UNSIGNED NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_school_video_1_idx` (`school_id` ASC),
  CONSTRAINT `fk_school_video_1`
    FOREIGN KEY (`school_id`)
    REFERENCES `school` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `task`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `task` ;

CREATE TABLE IF NOT EXISTS `task` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(45) NULL DEFAULT NULL,
  `content` TEXT NULL DEFAULT NULL,
  `start` DATETIME NULL DEFAULT NULL,
  `end` DATETIME NULL DEFAULT NULL,
  `creator_id` INT(10) UNSIGNED NULL DEFAULT NULL,
  `created_date` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_calendar_1_idx` (`creator_id` ASC),
  CONSTRAINT `fk_calendar_1`
    FOREIGN KEY (`creator_id`)
    REFERENCES `user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `task_share`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `task_share` ;

CREATE TABLE IF NOT EXISTS `task_share` (
  `task_id` INT(10) UNSIGNED NOT NULL,
  `user_id` INT(10) UNSIGNED NOT NULL,
  PRIMARY KEY (`task_id`, `user_id`),
  INDEX `fk_calendar_share_2_idx` (`user_id` ASC),
  CONSTRAINT `fk_calendar_share_1`
    FOREIGN KEY (`task_id`)
    REFERENCES `task` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_calendar_share_2`
    FOREIGN KEY (`user_id`)
    REFERENCES `user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `thread`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `thread` ;

CREATE TABLE IF NOT EXISTS `thread` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(512) NULL DEFAULT NULL,
  `user_id` INT(10) UNSIGNED NULL DEFAULT NULL,
  `course_id` INT(10) UNSIGNED NULL DEFAULT NULL,
  `item_id` INT UNSIGNED NULL,
  `created_date` DATETIME NULL DEFAULT NULL,
  `deleted_date` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_thread_1_idx` (`course_id` ASC),
  INDEX `fk_thread_2_idx` (`user_id` ASC),
  INDEX `fk_thread_3_idx` (`item_id` ASC),
  CONSTRAINT `fk_thread_1`
    FOREIGN KEY (`course_id`)
    REFERENCES `course` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_thread_2`
    FOREIGN KEY (`user_id`)
    REFERENCES `user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_thread_3`
    FOREIGN KEY (`item_id`)
    REFERENCES `item` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `thread_message`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `thread_message` ;

CREATE TABLE IF NOT EXISTS `thread_message` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `message` TEXT NULL DEFAULT NULL,
  `user_id` INT(10) UNSIGNED NULL DEFAULT NULL,
  `thread_id` INT(10) UNSIGNED NULL DEFAULT NULL,
  `parent_id` INT UNSIGNED NULL,
  `created_date` DATETIME NULL DEFAULT NULL,
  `deleted_date` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_thread_message_1_idx` (`user_id` ASC),
  INDEX `fk_thread_message_2_idx` (`thread_id` ASC),
  INDEX `fk_thread_message_3_idx` (`parent_id` ASC),
  CONSTRAINT `fk_thread_message_1`
    FOREIGN KEY (`user_id`)
    REFERENCES `user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_thread_message_2`
    FOREIGN KEY (`thread_id`)
    REFERENCES `thread` (`id`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE,
  CONSTRAINT `fk_thread_message_3`
    FOREIGN KEY (`parent_id`)
    REFERENCES `thread_message` (`id`)
    ON DELETE NO ACTION
    ON UPDATE SET NULL)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `user_language`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `user_language` ;

CREATE TABLE IF NOT EXISTS `user_language` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `user_id` INT(10) UNSIGNED NOT NULL,
  `language_id` INT(10) UNSIGNED NOT NULL,
  `language_level_id` INT(10) UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `unique_user_language` (`user_id` ASC, `language_id` ASC),
  INDEX `fk_user_language_2_idx` (`language_id` ASC),
  INDEX `fk_user_language_3_idx` (`language_level_id` ASC),
  CONSTRAINT `fk_user_language_1`
    FOREIGN KEY (`user_id`)
    REFERENCES `user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_language_2`
    FOREIGN KEY (`language_id`)
    REFERENCES `language` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_language_3`
    FOREIGN KEY (`language_level_id`)
    REFERENCES `language_level` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `user_role`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `user_role` ;

CREATE TABLE IF NOT EXISTS `user_role` (
  `user_id` INT(10) UNSIGNED NOT NULL,
  `role_id` INT(10) UNSIGNED NOT NULL,
  PRIMARY KEY (`user_id`, `role_id`),
  INDEX `fk_user_role_2_idx` (`role_id` ASC),
  CONSTRAINT `fk_user_role_1`
    FOREIGN KEY (`user_id`)
    REFERENCES `user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_role_2`
    FOREIGN KEY (`role_id`)
    REFERENCES `role` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `videoconf_opt`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `videoconf_opt` ;

CREATE TABLE IF NOT EXISTS `videoconf_opt` (
  `item_id` INT UNSIGNED NOT NULL,
  `record` TINYINT(1) NOT NULL DEFAULT 1,
  `nb_user_autorecord` INT NOT NULL DEFAULT 2,
  `allow_intructor` TINYINT(1) NOT NULL DEFAULT 1,
  PRIMARY KEY (`item_id`),
  CONSTRAINT `fk_opt_assignment_10`
    FOREIGN KEY (`item_id`)
    REFERENCES `item` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `videoconf`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `videoconf` ;

CREATE TABLE IF NOT EXISTS `videoconf` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `token` TEXT NULL DEFAULT NULL,
  `start_date` DATETIME NULL DEFAULT NULL,
  `duration` INT(11) NULL DEFAULT NULL,
  `archive_token` TEXT NULL DEFAULT NULL,
  `archive_link` TEXT NULL DEFAULT NULL,
  `archive_status` VARCHAR(128) NULL DEFAULT NULL,
  `status` VARCHAR(45) NULL DEFAULT NULL,
  `conversation_id` INT(10) UNSIGNED NULL DEFAULT NULL,
  `submission_id` INT(10) UNSIGNED NULL DEFAULT NULL,
  `title` VARCHAR(256) NULL DEFAULT NULL,
  `description` TEXT NULL DEFAULT NULL,
  `created_date` DATETIME NULL DEFAULT NULL,
  `deleted_date` DATETIME NULL DEFAULT NULL,
  `videoconf_opt` INT UNSIGNED NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_videoconf_1_idx` (`conversation_id` ASC),
  INDEX `fk_videoconf_2_idx` (`submission_id` ASC),
  INDEX `fk_videoconf_3_idx` (`videoconf_opt` ASC),
  CONSTRAINT `fk_videoconf_1`
    FOREIGN KEY (`conversation_id`)
    REFERENCES `conversation` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_videoconf_2`
    FOREIGN KEY (`submission_id`)
    REFERENCES `submission` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_videoconf_3`
    FOREIGN KEY (`videoconf_opt`)
    REFERENCES `videoconf_opt` (`item_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `videoconf_admin`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `videoconf_admin` ;

CREATE TABLE IF NOT EXISTS `videoconf_admin` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `videoconf_id` INT(10) UNSIGNED NULL DEFAULT NULL,
  `user_id` INT(11) NULL DEFAULT NULL,
  `token` TEXT NULL DEFAULT NULL,
  `created_date` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_videoconf_admin_vodeoconf_idx` (`videoconf_id` ASC),
  CONSTRAINT `fk_videoconf_admin_vodeoconf`
    FOREIGN KEY (`videoconf_id`)
    REFERENCES `videoconf` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `videoconf_archive`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `videoconf_archive` ;

CREATE TABLE IF NOT EXISTS `videoconf_archive` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `archive_token` TEXT NULL DEFAULT NULL,
  `archive_link` TEXT NULL DEFAULT NULL,
  `archive_status` VARCHAR(128) NULL DEFAULT NULL,
  `archive_duration` INT(11) NULL DEFAULT NULL,
  `videoconf_id` INT(10) UNSIGNED NULL DEFAULT NULL,
  `created_date` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_videoconf_archive_1_idx` (`videoconf_id` ASC),
  CONSTRAINT `fk_videoconf_archive_1`
    FOREIGN KEY (`videoconf_id`)
    REFERENCES `videoconf` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `videoconf_conversation`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `videoconf_conversation` ;

CREATE TABLE IF NOT EXISTS `videoconf_conversation` (
  `videoconf_id` INT(10) UNSIGNED NOT NULL,
  `conversation_id` INT(10) UNSIGNED NOT NULL,
  PRIMARY KEY (`videoconf_id`, `conversation_id`),
  INDEX `fk_videoconf_conversation_1_idx` (`conversation_id` ASC),
  CONSTRAINT `fk_videoconf_conversation_1`
    FOREIGN KEY (`conversation_id`)
    REFERENCES `conversation` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_videoconf_conversation_2`
    FOREIGN KEY (`videoconf_id`)
    REFERENCES `videoconf` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `videoconf_doc`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `videoconf_doc` ;

CREATE TABLE IF NOT EXISTS `videoconf_doc` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `videoconf_id` INT(10) UNSIGNED NOT NULL,
  `token` VARCHAR(45) NOT NULL,
  `name` VARCHAR(255) NULL DEFAULT NULL,
  `created_date` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_videoconf_doc_1_idx` (`videoconf_id` ASC),
  CONSTRAINT `fk_videoconf_doc_1`
    FOREIGN KEY (`videoconf_id`)
    REFERENCES `videoconf` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `videoconf_entity`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `videoconf_entity` ;

CREATE TABLE IF NOT EXISTS `videoconf_entity` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `videoconf_id` INT(10) UNSIGNED NULL DEFAULT NULL,
  `name` VARCHAR(128) NULL DEFAULT NULL,
  `avatar` VARCHAR(128) NULL DEFAULT NULL,
  `token` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_videoconf_entity_videoconf_idx` (`videoconf_id` ASC),
  CONSTRAINT `fk_videoconf_entity_videoconf`
    FOREIGN KEY (`videoconf_id`)
    REFERENCES `videoconf` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `videoconf_invitation`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `videoconf_invitation` ;

CREATE TABLE IF NOT EXISTS `videoconf_invitation` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `videoconf_entity_id` INT(10) UNSIGNED NULL DEFAULT NULL,
  `firstname` VARCHAR(128) NULL DEFAULT NULL,
  `lastname` VARCHAR(128) NULL DEFAULT NULL,
  `avatar` VARCHAR(128) NULL DEFAULT NULL,
  `email` VARCHAR(128) NULL DEFAULT NULL,
  `utc` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_videoconf_invitation_videoconf_entity_idx` (`videoconf_entity_id` ASC),
  CONSTRAINT `fk_videoconf_invitation_videoconf_entity`
    FOREIGN KEY (`videoconf_entity_id`)
    REFERENCES `videoconf_entity` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `ct_date`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ct_date` ;

CREATE TABLE IF NOT EXISTS `ct_date` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `item_id` INT UNSIGNED NOT NULL,
  `date` DATETIME NOT NULL,
  `after` TINYINT(1) NOT NULL DEFAULT 1,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  CONSTRAINT `fk_ct_date_1`
    FOREIGN KEY (`item_id`)
    REFERENCES `item` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `ct_done`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ct_done` ;

CREATE TABLE IF NOT EXISTS `ct_done` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `item_id` INT UNSIGNED NOT NULL,
  `target_id` INT UNSIGNED NOT NULL,
  `all` TINYINT(1) NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  INDEX `done_index3` (`item_id` ASC),
  INDEX `done_index4` (`target_id` ASC),
  UNIQUE INDEX `done_uique1` (`item_id` ASC, `target_id` ASC),
  CONSTRAINT `fk_ct_done_1`
    FOREIGN KEY (`item_id`)
    REFERENCES `item` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ct_done_2`
    FOREIGN KEY (`target_id`)
    REFERENCES `item` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `group`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `group` ;

CREATE TABLE IF NOT EXISTS `group` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `uid` VARCHAR(80) NULL,
  `name` VARCHAR(80) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `ct_group`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ct_group` ;

CREATE TABLE IF NOT EXISTS `ct_group` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `item_id` INT UNSIGNED NULL,
  `group_id` INT UNSIGNED NULL,
  `set_id` INT NULL,
  `belongs` TINYINT(1) NOT NULL DEFAULT 1,
  PRIMARY KEY (`id`),
  INDEX `fk_ct_group_2_idx` (`group_id` ASC),
  CONSTRAINT `fk_ct_group_1`
    FOREIGN KEY (`item_id`)
    REFERENCES `item` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ct_group_2`
    FOREIGN KEY (`group_id`)
    REFERENCES `group` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `ct_rate`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ct_rate` ;

CREATE TABLE IF NOT EXISTS `ct_rate` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `item_id` INT UNSIGNED NULL,
  `inf` INT NULL,
  `sup` INT NULL,
  `target_id` INT UNSIGNED NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_ct_rate_2_idx` (`target_id` ASC),
  UNIQUE INDEX `item_id_UNIQUE` (`item_id` ASC, `target_id` ASC),
  CONSTRAINT `fk_ct_rate_1`
    FOREIGN KEY (`item_id`)
    REFERENCES `item` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ct_rate_2`
    FOREIGN KEY (`target_id`)
    REFERENCES `item` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `submission_user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `submission_user` ;

CREATE TABLE IF NOT EXISTS `submission_user` (
  `submission_id` INT UNSIGNED NOT NULL,
  `user_id` INT UNSIGNED NOT NULL,
  `grade` INT NULL,
  `submit_date` DATETIME NULL,
  PRIMARY KEY (`submission_id`, `user_id`),
  UNIQUE INDEX `index3` (`submission_id` ASC, `user_id` ASC),
  INDEX `fk_submission_user_2_idx` (`user_id` ASC),
  CONSTRAINT `fk_submission_user_1`
    FOREIGN KEY (`submission_id`)
    REFERENCES `submission` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_submission_user_2`
    FOREIGN KEY (`user_id`)
    REFERENCES `user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `group_user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `group_user` ;

CREATE TABLE IF NOT EXISTS `group_user` (
  `group_id` INT UNSIGNED NOT NULL,
  `user_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`group_id`, `user_id`),
  INDEX `fk_group_user_2_idx` (`user_id` ASC),
  CONSTRAINT `fk_group_user_1`
    FOREIGN KEY (`group_id`)
    REFERENCES `group` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_group_user_2`
    FOREIGN KEY (`user_id`)
    REFERENCES `user` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `set_group`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `set_group` ;

CREATE TABLE IF NOT EXISTS `set_group` (
  `set_id` INT UNSIGNED NOT NULL,
  `group_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`set_id`, `group_id`),
  INDEX `fk_set_group_2_idx` (`group_id` ASC),
  CONSTRAINT `fk_set_group_1`
    FOREIGN KEY (`set_id`)
    REFERENCES `set` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_set_group_2`
    FOREIGN KEY (`group_id`)
    REFERENCES `group` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `opt_grading`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `opt_grading` ;

CREATE TABLE IF NOT EXISTS `opt_grading` (
  `item_id` INT UNSIGNED NOT NULL,
  `mode` ENUM('instructor', 'average', 'none') NOT NULL DEFAULT 'instructor',
  `has_pg` TINYINT(1) NULL,
  `pg_nb` INT(11) NULL,
  `pg_auto` TINYINT(1) NULL DEFAULT 0,
  `pg_due_date` DATETIME NULL,
  `pg_can_view` TINYINT(1) NULL DEFAULT 0,
  `user_can_view` TINYINT(1) NULL DEFAULT 0,
  `pg_stars` TINYINT(1) NULL DEFAULT 0,
  PRIMARY KEY (`item_id`),
  CONSTRAINT `fk_opt_assignment_1`
    FOREIGN KEY (`item_id`)
    REFERENCES `item` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bank_question_item`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bank_question_item` ;

CREATE TABLE IF NOT EXISTS `bank_question_item` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `libelle` TEXT NULL DEFAULT NULL,
  `bank_question_id` INT(10) UNSIGNED NULL,
  `order_id` INT(10) UNSIGNED NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_bank_question_item_1_idx` (`bank_question_id` ASC),
  INDEX `fk_bank_question_item_2_idx` (`order_id` ASC),
  CONSTRAINT `fk_bank_question_item_1`
    FOREIGN KEY (`bank_question_id`)
    REFERENCES `bank_question` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_bank_question_item_2`
    FOREIGN KEY (`order_id`)
    REFERENCES `bank_question_item` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bank_answer_item`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bank_answer_item` ;

CREATE TABLE IF NOT EXISTS `bank_answer_item` (
  `bank_question_item_id` INT(10) UNSIGNED NOT NULL,
  `percent` INT NULL,
  `answer` TEXT NULL DEFAULT NULL,
  `date` DATE NULL DEFAULT NULL,
  `time` TIME NULL DEFAULT NULL,
  INDEX `fk_poll_answer_items_20_idx` (`bank_question_item_id` ASC),
  CONSTRAINT `fk_poll_answer_items_20`
    FOREIGN KEY (`bank_question_item_id`)
    REFERENCES `bank_question_item` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `question_relation`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `question_relation` ;

CREATE TABLE IF NOT EXISTS `question_relation` (
  `group_question_id` INT UNSIGNED NOT NULL,
  `bank_question_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`group_question_id`, `bank_question_id`),
  INDEX `fk_question_relation_2_idx` (`bank_question_id` ASC),
  CONSTRAINT `fk_question_relation_1`
    FOREIGN KEY (`group_question_id`)
    REFERENCES `group_question` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_question_relation_2`
    FOREIGN KEY (`bank_question_id`)
    REFERENCES `bank_question` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bank_question_tag`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bank_question_tag` ;

CREATE TABLE IF NOT EXISTS `bank_question_tag` (
  `bank_question_id` INT UNSIGNED NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  INDEX `fk_bank_question_tag_1_idx` (`bank_question_id` ASC),
  PRIMARY KEY (`bank_question_id`, `name`),
  UNIQUE INDEX `uq_tagbank` (`bank_question_id` ASC, `name` ASC),
  CONSTRAINT `fk_bank_question_tag_1`
    FOREIGN KEY (`bank_question_id`)
    REFERENCES `bank_question` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bank_question_media`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bank_question_media` ;

CREATE TABLE IF NOT EXISTS `bank_question_media` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `bank_question_id` INT UNSIGNED NOT NULL,
  `library_id` INT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_bank_question_media_1`
    FOREIGN KEY (`bank_question_id`)
    REFERENCES `bank_question` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `item_composant`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `item_composant` ;

CREATE TABLE IF NOT EXISTS `item_composant` (
  `item_id` INT UNSIGNED NOT NULL,
  `has_eqcq` TINYINT(1) NOT NULL DEFAULT 0,
  `has_conversation` TINYINT(1) NOT NULL DEFAULT 0,
  `has_videoconf` TINYINT(1) NOT NULL DEFAULT 0,
  `has_assigment` TINYINT(1) NOT NULL DEFAULT 0,
  `has_poll` TINYINT(1) NOT NULL DEFAULT 0,
  `has_document` TINYINT(1) NOT NULL DEFAULT 0,
  PRIMARY KEY (`item_id`),
  CONSTRAINT `fk_opt_1`
    FOREIGN KEY (`item_id`)
    REFERENCES `item` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `sub_question`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sub_question` ;

CREATE TABLE IF NOT EXISTS `sub_question` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `sub_quiz_id` INT UNSIGNED NOT NULL,
  `poll_item_id` INT(10) UNSIGNED NOT NULL,
  `bank_question_id` INT UNSIGNED NOT NULL,
  `group_question_id` INT UNSIGNED NULL,
  `point` VARCHAR(45) NULL,
  `answered_date` DATETIME NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_poll_answer_1_idx` (`poll_item_id` ASC),
  INDEX `fk_poll_answer_5_idx` (`group_question_id` ASC),
  INDEX `fk_sub_question_1_idx` (`sub_quiz_id` ASC),
  CONSTRAINT `fk_poll_answer_10`
    FOREIGN KEY (`poll_item_id`)
    REFERENCES `poll_item` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_poll_answer_50`
    FOREIGN KEY (`group_question_id`)
    REFERENCES `group_question` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_sub_question_1`
    FOREIGN KEY (`sub_quiz_id`)
    REFERENCES `sub_quiz` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Placeholder table for view `research`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `research` (`id` INT, `firstname` INT, `lastname` INT, `avatar` INT, `category` INT, `role` INT, `facette` INT);

-- -----------------------------------------------------
-- View `research`
-- -----------------------------------------------------
DROP VIEW IF EXISTS `research` ;
DROP TABLE IF EXISTS `research`;
CREATE  OR REPLACE VIEW `research` AS select `u`.`id` AS `id`,concat(`u`.`firstname`,' ',`u`.`lastname`) AS `firstname`,concat(`u`.`lastname`,' ',`u`.`firstname`) AS `lastname`,`u`.`avatar` AS `avatar`,'user' AS `category`,`role`.`name` AS `role`,if((`role`.`id` = 4),10,20) AS `facette` from ((`user` `u` join `user_role` `us`) join `role`) where ((`us`.`user_id` = `u`.`id`) and (`us`.`role_id` = `role`.`id`) and (`us`.`role_id` in (4,5)) and isnull(`u`.`deleted_date`)) union select `c`.`id` AS `id`,`c`.`title` AS `title`,`p`.`name` AS `name`,`c`.`picture` AS `picture`,'course' AS `category`,'' AS `role`,'30' AS `facette` from (`course` `c` join `program` `p`) where ((`c`.`program_id` = `p`.`id`) and isnull(`p`.`deleted_date`) and isnull(`c`.`deleted_date`)) union select `s`.`id` AS `id`,`s`.`name` AS `name`,`s`.`short_name` AS `short_name`,`s`.`logo` AS `logo`,'school' AS `category`,'' AS `role`,'40' AS `facette` from `school` `s` where isnull(`s`.`deleted_date`);

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
